Upgrade natives from 1.1.4 to 1.1.6
Without this, ‘npm install’ fails on Node ≥ 10.15.0 (to say nothing of
12.x or 14.x, which Gulp 3 doesn’t support at all):

$ npm install

> stacktrace-js@2.0.2 prepare /home/anders/js/stacktrace.js
> gulp dist

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/anders/js/stacktrace.js/node_modules/natives/index.js:137:5)
    at require (/home/anders/js/stacktrace.js/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/anders/js/stacktrace.js/node_modules/natives/index.js:137:5)
    at require (/home/anders/js/stacktrace.js/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/anders/js/stacktrace.js/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/anders/js/stacktrace.js/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/anders/js/stacktrace.js/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stacktrace-js@2.0.2 prepare: `gulp dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stacktrace-js@2.0.2 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anders/.npm/_logs/2021-03-25T00_14_18_635Z-debug.log

Signed-off-by: Anders Kaseorg <andersk@mit.edu>